package com.joel.biblewallpaper

data class Verse(val text: String, val reference: String)

object Verses {
    val all = listOf(
        Verse("The Lord is my shepherd; I shall not want.", "Psalm 23:1"),
        Verse("He leads me beside still waters. He restores my soul.", "Psalm 23:2-3"),
        Verse("The Lord is my light and my salvation; whom shall I fear?", "Psalm 27:1"),
        Verse("Wait for the Lord; be strong, and let your heart take courage.", "Psalm 27:14"),
        Verse("Taste and see that the Lord is good.", "Psalm 34:8"),
        Verse("God is our refuge and strength, a very present help in trouble.", "Psalm 46:1"),
        Verse("Be still, and know that I am God.", "Psalm 46:10"),
        Verse("Create in me a clean heart, O God.", "Psalm 51:10"),
        Verse("When I am afraid, I put my trust in You.", "Psalm 56:3"),
        Verse("Your steadfast love is better than life.", "Psalm 63:3"),
        Verse("This is the day that the Lord has made; let us rejoice and be glad in it.", "Psalm 118:24"),
        Verse("Your word is a lamp to my feet and a light to my path.", "Psalm 119:105"),
        Verse("The Lord will keep your going out and your coming in.", "Psalm 121:8"),
        Verse("Those who sow in tears shall reap with shouts of joy.", "Psalm 126:5"),
        Verse("The Lord is gracious and merciful, slow to anger and abounding in steadfast love.", "Psalm 145:8"),
        Verse("Trust in the Lord with all your heart.", "Proverbs 3:5"),
        Verse("In all your ways acknowledge Him, and He will make straight your paths.", "Proverbs 3:6"),
        Verse("Above all else, guard your heart.", "Proverbs 4:23"),
        Verse("The name of the Lord is a strong tower.", "Proverbs 18:10"),
        Verse("I have loved you with an everlasting love.", "Jeremiah 31:3"),
        Verse("The Lord is good to those who wait for Him.", "Lamentations 3:25"),
        Verse("Seek the Lord and live.", "Amos 5:6"),
        Verse("Act justly, love mercy, and walk humbly with your God.", "Micah 6:8"),
        Verse("The Lord your God is with you, the Mighty Warrior who saves.", "Zephaniah 3:17"),
        Verse("Blessed are the pure in heart, for they shall see God.", "Matthew 5:8"),
        Verse("You are the light of the world.", "Matthew 5:14"),
        Verse("Seek first the kingdom of God and His righteousness.", "Matthew 6:33"),
        Verse("Come to Me, all who labor and are heavy laden, and I will give you rest.", "Matthew 11:28"),
        Verse("With God all things are possible.", "Matthew 19:26"),
        Verse("I am with you always, to the end of the age.", "Matthew 28:20"),
        Verse("Do not fear, only believe.", "Mark 5:36"),
        Verse("For nothing will be impossible with God.", "Luke 1:37"),
        Verse("Glory to God in the highest, and on earth peace.", "Luke 2:14"),
        Verse("I am the bread of life.", "John 6:35"),
        Verse("I am the light of the world.", "John 8:12"),
        Verse("I am the good shepherd.", "John 10:11"),
        Verse("I am the resurrection and the life.", "John 11:25"),
        Verse("Peace I leave with you; My peace I give to you.", "John 14:27"),
        Verse("I am the vine; you are the branches.", "John 15:5"),
        Verse("Greater love has no one than this.", "John 15:13"),
        Verse("Rejoice in hope, be patient in tribulation, be constant in prayer.", "Romans 12:12"),
        Verse("If God is for us, who can be against us?", "Romans 8:31"),
        Verse("Love is patient and kind; love does not envy or boast.", "1 Corinthians 13:4"),
        Verse("Love never ends.", "1 Corinthians 13:8"),
        Verse("Walk by faith, not by sight.", "2 Corinthians 5:7"),
        Verse("My grace is sufficient for you.", "2 Corinthians 12:9"),
        Verse("The fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness.", "Galatians 5:22"),
        Verse("Be kind to one another, tenderhearted, forgiving one another.", "Ephesians 4:32"),
        Verse("Rejoice in the Lord always.", "Philippians 4:4"),
        Verse("Do not be anxious about anything.", "Philippians 4:6"),
        Verse("The peace of God will guard your hearts and your minds.", "Philippians 4:7"),
        Verse("I can do all things through Christ who strengthens me.", "Philippians 4:13"),
        Verse("Set your minds on things above.", "Colossians 3:2"),
        Verse("Whatever you do, do it heartily, as for the Lord.", "Colossians 3:23"),
        Verse("Pray without ceasing.", "1 Thessalonians 5:17"),
        Verse("Give thanks in all circumstances.", "1 Thessalonians 5:18"),
        Verse("God gave us a spirit not of fear but of power and love.", "2 Timothy 1:7"),
        Verse("Let us run with endurance the race that is set before us.", "Hebrews 12:1"),
        Verse("Jesus Christ is the same yesterday and today and forever.", "Hebrews 13:8"),
        Verse("Every good and perfect gift is from above.", "James 1:17"),
        Verse("Humble yourselves before the Lord, and He will lift you up.", "James 4:10"),
        Verse("Cast all your anxiety on Him because He cares for you.", "1 Peter 5:7"),
        Verse("God is light, and in Him is no darkness at all.", "1 John 1:5"),
        Verse("We love because He first loved us.", "1 John 4:19"),
        Verse("Behold, I am making all things new.", "Revelation 21:5")
    )
}
